source "https://rubygems.org"

gem "minima", "~> 2.0"

gem "netrc"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-github-metadata"

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
